name: Deployment

on:
  push:
    branches:
     - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Configure SSH
              run: |
                mkdir -p ~/.ssh/
                echo "$DEPLOY_KEY" > ~/.ssh/staging.key
                chmod 600 ~/.ssh/staging.key
                ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts 
                cat >>~/.ssh/config <<END
                Host staging
                  HostName $DEPLOYING_SERVER
                  User $SERVER_HOST
                  IdentityFile ~/.ssh/staging.key
                  StrictHostKeyChecking no
                END
                ssh staging "git pull; docker-compose up -d"
              env: 
                SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
                SERVER_HOST: ${{ secrets.SERVER_HOST }}
                DEPLOYING_SERVER: ${{ secrets.DEPLOYING_SERVER }}